# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ecegrid/a/ee364h10/ee364h10/Prelab10/calculator.ui'
#
# Created: Mon Mar 30 18:57:30 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 375)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_7 = QtGui.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(20, 90, 71, 31))
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtGui.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(110, 90, 71, 31))
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtGui.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 90, 71, 31))
        self.btn_9.setObjectName("btn_9")
        self.btn_div = QtGui.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(290, 90, 71, 31))
        self.btn_div.setObjectName("btn_div")
        self.btn_4 = QtGui.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(20, 130, 71, 31))
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtGui.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(110, 130, 71, 31))
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtGui.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 130, 71, 31))
        self.btn_6.setObjectName("btn_6")
        self.btn_multiply = QtGui.QPushButton(self.centralwidget)
        self.btn_multiply.setGeometry(QtCore.QRect(290, 130, 71, 31))
        self.btn_multiply.setObjectName("btn_multiply")
        self.btn_1 = QtGui.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(20, 170, 71, 31))
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtGui.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(110, 170, 71, 31))
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtGui.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 170, 71, 31))
        self.btn_3.setObjectName("btn_3")
        self.btn_sub = QtGui.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(290, 170, 71, 31))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_0 = QtGui.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(20, 210, 161, 31))
        self.btn_0.setObjectName("btn_0")
        self.btn_decimal = QtGui.QPushButton(self.centralwidget)
        self.btn_decimal.setGeometry(QtCore.QRect(200, 210, 71, 31))
        self.btn_decimal.setObjectName("btn_decimal")
        self.btn_add = QtGui.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(290, 210, 71, 31))
        self.btn_add.setObjectName("btn_add")
        self.btn_clear = QtGui.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(400, 90, 91, 71))
        self.btn_clear.setObjectName("btn_clear")
        self.btn_equals = QtGui.QPushButton(self.centralwidget)
        self.btn_equals.setGeometry(QtCore.QRect(400, 170, 91, 71))
        self.btn_equals.setObjectName("btn_equals")
        self.main_output = QtGui.QLineEdit(self.centralwidget)
        self.main_output.setGeometry(QtCore.QRect(20, 20, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.main_output.setFont(font)
        self.main_output.setText("")
        self.main_output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_output.setObjectName("main_output")
        self.label_decimal = QtGui.QLabel(self.centralwidget)
        self.label_decimal.setGeometry(QtCore.QRect(30, 290, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_decimal.setFont(font)
        self.label_decimal.setStyleSheet("border:none")
        self.label_decimal.setObjectName("label_decimal")
        self.spinBox_decimals = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_decimals.setEnabled(True)
        self.spinBox_decimals.setGeometry(QtCore.QRect(140, 290, 41, 21))
        self.spinBox_decimals.setMaximum(5)
        self.spinBox_decimals.setObjectName("spinBox_decimals")
        self.checkBox_thousands = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_thousands.setGeometry(QtCore.QRect(260, 290, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_thousands.setFont(font)
        self.checkBox_thousands.setStyleSheet("border:none")
        self.checkBox_thousands.setObjectName("checkBox_thousands")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_div.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_multiply.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sub.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_decimal.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_equals.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_decimal.setText(QtGui.QApplication.translate("MainWindow", "Decimal Digits", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_thousands.setText(QtGui.QApplication.translate("MainWindow", "Display Thousands\' Separator", None, QtGui.QApplication.UnicodeUTF8))

